#include <windows.h>

// Forward declaration of the original entry point generated by Ghidra.
extern void entry(void);

int main(int argc, char *argv[])
{
    // The original decompiled code expects the Windows process environment.
    // We simply forward to the existing entry() function which performs its own
    // argument parsing, initialization and eventual termination via _exit().
    // The return value is never used because _exit() does not return, but we
    // provide a fallback for non‑Windows platforms.
    entry();
    return 0; // Should never be reached
}
